# Generated by Django 3.2 on 2021-04-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pieces',
            new_name='Piece',
        ),
    ]
