# Generated by Django 3.2 on 2021-04-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0002_rename_pieces_piece'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piece',
            old_name='creator',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='piece',
            old_name='cid',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='piece',
            old_name='path',
            new_name='media_url',
        ),
        migrations.AddField(
            model_name='piece',
            name='eth_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
