# Generated by Django 3.2 on 2021-04-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0003_auto_20210415_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='piece',
            name='id_number',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
