# Generated by Django 3.2 on 2021-04-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0005_alter_piece_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='type_of_piece',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
